user:
  name:
    max_length: 50
  email:
    max_length: 127
  password:
    min_length: 6
  per_page: 30
  post:
    per_page: 10
  gravatar:
    size_32: 32
    size_40: 40
    size_50: 50
    size_80: 80
post:
  content:
    max_length: 1000
  title:
    max_length: 140
comment:
  content:
    max_length: 140
tag:
  name:
    max_length: 20
picture:
  file_type: "image/jpeg, image/gif, image/png"
following:
  per_page: 30
follower:
  per_page: 30
